name: Update gist with WakaTime stats
on:
  pull_request_review:
    types: [submitted]
    branches: ['master']
    paths: ['**path/**']
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: mickeypash/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 44012add4bab7dd28efeb70ec1f26da9
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
